version: '3.8'
services:
  db:
    container_name: postgres-souls-price
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: souls_price_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5438:5432'

volumes:
  postgres_data: